### ISSUE TITLE
setup & use

### ISSUE THREAD

**Issue by ajonno** [hansemannn/react-native-storekit#1]
hi there, do you have any info on how to use this lib ? I'm experienced with React Native but didn't want to make any assumptions. Also are you using this in prod ?

**Comment by andrewmarmion** [comment]
I would also like the answers to the above questions.

**Comment by hansemannn** [comment]
I discontinued this version in favor of the [Titanium version](https://github.com/appcelerator-modules/ti.storekit) that is more up to date.
